name: ad_hoc_ident_ocr_camera
description: "Provides basic camera input capabilities for the ad_hoc_ident framework."
version: 0.0.1-preview-1
homepage: https://github.com/FabianMoeckel/ad_hoc_ident_ocr_camera
repository: https://github.com/FabianMoeckel/ad_hoc_ident_ocr_camera

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+1
  ad_hoc_ident_ocr: ^0.0.1-preview-1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
